print("hello, arcomlib server test env!")
local arcom = dofile( "/lib/arcomlib.lua" )
arcom.initServer("testServer", "top")
arcom.regMainLoop(	function()
						print( "This is main loop!" )
						sleep(1)
					end)
arcom.regInterrupt(	function(msg)
						print( "This is ISR hello." )
						print("your msg is "..tostring( msg ))
						if msg == "int" then arcom.innerInterrupt("disable"); print("self int!") end
					end, "hello")
arcom.regSafetyWatchdog( function()
					print( "Safety watcher is running." )
					sleep(3)
end )
arcom.startServer()
